### ISSUE TITLE
有个bug，不知作者以及各位user遇到过没有，见内

### ISSUE THREAD

**Issue by hushenshen** [jerrymakesjelly/autoremove-torrents#10]
定义两个策略，跑脚本发现，只有第一个策略生效，第二个策略不生效，并且log打印两遍

我的配置如下：
```
task_OB: 
  client: qbittorrent
  host: ******
  username: ****
  password: ******
  strategies:
    strategy_MT:
      trackers: https://tp.m-team.cc
      ratio: 1
      seeding_time: 180000
    strategy_OB:
      trackers: https://ourbits.club
      ratio: 1
      seed_size:
        limit: 1024
        action: remove-old-seeds
      create_time: 86400
      seeding_time: 7200    
  delete_data: true
```

LOG如下:

Sun, 28 Oct 2018 16:50:19 autoremovetorrents.main INFO: Auto Remove Torrents 1.2.4
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.main INFO: Loading configurations...
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.task INFO: Logging in...
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v4.1.1.
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.task INFO: Getting all the torrents...
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.task INFO: Found 6 seed(s) in the client.
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.strategy INFO: Running strategy strategy_MT...
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.strategy INFO: Total: 1 seed(s). 0 seed(s) can be removed.
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.strategy INFO: Running strategy strategy_OB...
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.strategy INFO: Running strategy strategy_OB...
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.strategy INFO: Total: 0 seed(s). 0 seed(s) can be removed.
Sun, 28 Oct 2018 16:50:19 autoremovetorrents.strategy INFO: Total: 0 seed(s). 0 seed(s) can be removed.

事实上OB的种子有6个，一个满足删除条件，可脚本没有识别出来

PS.才发现作者是我邮校友，顺祝考研成功
