### ISSUE TITLE
[Feature Request] 仿照 `remove`，新增 `reannounce` 功能以进行 tracker 汇报

### ISSUE THREAD

**Issue by ludoux** [jerrymakesjelly/autoremove-torrents#130]
与 https://github.com/jerrymakesjelly/autoremove-torrents/issues/59 相类似。假如作者之后引入了 tracker 汇报相关代码，希望在配置中支持 `reannounce` 功能，可以手动写表达式（与 `remove` 类似）并进行强制 tracker 汇报

**Comment by else05** [comment]
血书这个功能，我磁盘空间小，下载太快，很多数据在磁盘不足时会删除 ，这时没有强制汇报数据到tracker ,会有很多上传数据没有同步上去，我测试了两个大站，上传快时，强制汇总报有接近100G数据同步到上传中，为了功能早日上线，开个捐赠我支持下大佬，

**Comment by else05** [comment]
@jerrymakesjelly

**Comment by ludoux** [comment]
为有类似需求的各位，我**尝试**（不保证没有 bug）在我的 [Fork](https://github.com/ludoux/autoremove-torrents) 里增加了 `reannounce` 字段，参考 https://github.com/jerrymakesjelly/autoremove-torrents/commit/a578b90094fa1826333afd150c1e9fbddc12d242 和 https://github.com/jerrymakesjelly/autoremove-torrents/commit/24a3227f74281e873cc29cd6ab04d647093ed76e 这两个提交。配置参考如下（刷流目的，刚加种和快删除前多次强制汇报）：
```
qb_task:
  client: qbittorrent
  host: http://192.168.2.214:8080
  strategies:
    strategy1:
      categories:
        - rss
      remove: progress > 99 and ( seeding_time > 1200 )
      remove: progress > 99 and ( seeding_time > 600 or upload_speed < 128 )
      remote_free_space:
        min: 20
        path: ""
        action: remove-inactive-seeds
    strategy2:
      reannounce: create_time < 960
      reannounce: progress > 94 and ( download_speed > 1 )
      reannounce: progress > 99 and ( download_speed < 128 )
  delete_data: true
```
