### ISSUE TITLE
qBittorrent 4.4.2 - delete data before completion

### ISSUE THREAD

**Issue by Jorman** [jerrymakesjelly/autoremove-torrents#131]
Hi, I just had a strange error, never happen before, maybe only a coincidence?

The torrent, in downloading mode, was deleted, but the configuration is always the same from about 2 years.
This's the part of the log:
```
Mon, 02 May 2022 21:33:06 main.py[line:51] INFO Auto Remove Torrents 1.5.3
Mon, 02 May 2022 21:33:06 main.py[line:53] INFO Loading configurations...
Mon, 02 May 2022 21:33:06 main.py[line:56] INFO Found 1 task(s) in the file.
Mon, 02 May 2022 21:33:06 task.py[line:138] INFO Running task 'qBittorrent'...
Mon, 02 May 2022 21:33:06 task.py[line:85] INFO Logging in...
Mon, 02 May 2022 21:33:06 task.py[line:87] INFO Login successfully. The client is qBittorrent v4.4.2.
Mon, 02 May 2022 21:33:06 task.py[line:88] INFO WebUI API version: 2.8.5 (v2)
Mon, 02 May 2022 21:33:06 task.py[line:92] INFO Status reported by the client: 
	Download Speed: 16.20MiB/s	Total: 44.56GiB
	Upload Speed: 300.99KiB/s	Total: 18.47GiB
	Outgoing Port Status: Open
Mon, 02 May 2022 21:33:06 task.py[line:96] INFO Getting all the torrents...
Mon, 02 May 2022 21:33:07 task.py[line:103] INFO Please wait...We have found 28 torrent(s).
Mon, 02 May 2022 21:33:08 task.py[line:103] INFO Please wait...We have found 83 torrent(s).
Mon, 02 May 2022 21:33:08 task.py[line:106] INFO Found 84 torrent(s) in the client.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-1...
Mon, 02 May 2022 21:33:08 strategy.py[line:172] INFO Total: 0 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-2...
Mon, 02 May 2022 21:33:08 strategy.py[line:172] INFO Total: 0 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-3...
Mon, 02 May 2022 21:33:08 strategy.py[line:172] INFO Total: 21 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-4...
Mon, 02 May 2022 21:33:08 strategy.py[line:172] INFO Total: 0 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-5...
Mon, 02 May 2022 21:33:08 strategy.py[line:172] INFO Total: 0 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-6...
Mon, 02 May 2022 21:33:08 strategy.py[line:172] INFO Total: 0 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-7...
Mon, 02 May 2022 21:33:08 strategy.py[line:172] INFO Total: 0 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-8...
Mon, 02 May 2022 21:33:08 strategy.py[line:172] INFO Total: 0 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:08 strategy.py[line:165] INFO Running strategy Private-Tracker-9...
Mon, 02 May 2022 21:33:09 strategy.py[line:172] INFO Total: 0 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:09 strategy.py[line:165] INFO Running strategy Private-Tracker-10...
Mon, 02 May 2022 21:33:09 strategy.py[line:172] INFO Total: 55 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:09 strategy.py[line:165] INFO Running strategy Private-Tracker-11...
Mon, 02 May 2022 21:33:09 strategy.py[line:172] INFO Total: 1 torrent(s). 0 torrent(s) can be removed.
Mon, 02 May 2022 21:33:09 strategy.py[line:165] INFO Running strategy Global-Tracker...
Mon, 02 May 2022 21:33:09 strategy.py[line:172] INFO Total: 6 torrent(s). 1 torrent(s) can be removed.
Mon, 02 May 2022 21:33:09 strategy.py[line:175] INFO To be deleted:
Mon, 02 May 2022 21:33:09 strategy.py[line:177] INFO Jurassic Park III (2001) 2160p H265 10 bit ita eng AC3 5.1 sub ita eng Licdom.mkv
	Progress:5.63%	Size:8.55GiB	Ratio:1.349	Total Uploaded:666.50MiB
	Seeder(connected/total):3/1	Leecher(connected/total):6/6	Status:Downloading
	Download Speed:112.27KiB/s(Avg.:302.43KiB/s)	Upload Speed:0.00B/s(Avg.:407.95KiB/s)
	Create Time:2022-05-02 21:05:13	Seeding Time:0d 00:00:00	Last Activity:2022-05-02 21:32:54
	Category:Film	Tracker:** [DHT] **,** [PeX] **,** [LSD] **,***
Mon, 02 May 2022 21:33:09 task.py[line:125] INFO The torrent Jurassic Park III (2001) 2160p H265 10 bit ita eng AC3 5.1 sub ita eng Licdom.mkv and its data have been removed.
```
And this's the part of the configuration:
```
qBittorrent:
  client: qbittorrent
  host: http://10.0.0.100:8081
  strategies:
    Global-Tracker:
      categories:
        - Film
        - Serie_Tv
      excluded_trackers:
        - tracker1
        - tracker2
        - tracker3
      remove: seeding_time > 86400 or ratio > 1
  delete_data: true
```
What I can do?
Do you need some extra logs?

J

**Comment by jerrymakesjelly** [comment]
Hi Jorman. According to your logs, the reason your torrent was removed is because its ratio reached 1.

Please note that since version 1.4.0, we removed status restriction in `ratio` condition, so a downloading torrent can also be removed as long as its ratio reaches the limitation.

To solve this problem, please use the `excluded_status` filter to exclude the downloading torrents, i.e.

```yaml
qBittorrent:
  client: qbittorrent
  host: http://10.0.0.100:8081
  strategies:
    Global-Tracker:
      categories:
        - Film
        - Serie_Tv
      excluded_trackers:
        - tracker1
        - tracker2
        - tracker3
      excluded_status:
        - Downloading
      remove: seeding_time > 86400 or ratio > 1
  delete_data: true
```

Hope this reply can help you solve this problem.
