### ISSUE TITLE
Config help: remove torrents above some ratio only until seed_size limit

### ISSUE THREAD

**Issue by gennaios** [jerrymakesjelly/autoremove-torrents#158]
Hi,

I'm trying to configure autoremove-torrents to limit torrents for a certain tracker to some seed_size. For such, are other criteria possible such as remove only if ratio or seed time above some interval?

I have the following config:

```
my_task:
  client: qbittorrent
  host: http://127.0.0.1:port
  username: user
  password: pass
  strategies:
    strategy_tracker1:
      trackers:
        - tracker.url
      ratio: 1.1
      seed_size:
        limit: 500
        action: remove-active-seeds
      delete_data: true
```

I'd like to keep seeded torrents for that tracker at `seed_size` some limit. Yet when running it, it removes all torrents above specified `ratio` while ignoring the `seed_size` limit. Thus all torrents above some `ratio` are removed, as if `seed_size` has no effect when both are specified. I've tried `remove: ratio > x` and that didn't do it.

Assistance would be very helpful. Thanks.

**Comment by gennaios** [comment]
I think I understand how it works.

What I'm hoping for is to limit seed_size to some number, and if above, remove only those with some conditions. Such as:

```
  strategies:
    strategy_btn:
      trackers:
        - landof.tv
      seed_size:
        limit: 850
        remove: ratio > 1.1
        action: remove-old-seeds # will this remove oldest first?
      delete_data: true
```
