### ISSUE TITLE
完善文档，希望能加入action详细说明

### ISSUE THREAD

**Issue by lhbdhr** [jerrymakesjelly/autoremove-torrents#165]
像是 remove-old-seeds、remove-inactive-seeds、remove-slow-upload-seeds
都不知道具体的数字是多少啊。

```yml
delete_by_slow_upload:
      action: remove-slow-upload-seeds
delete_by_restspace:
      free_space:
        min: 100 # size in GiB
        path: /torrents/qbittorrent/
        action: remove-old-seeds
```
我是阅读https://autoremove-torrents.readthedocs.io/zh_CN/latest/config.html#part-i-strategy-name 文档的
remove-slow-upload-seeds的速度到底是多少啊？我看autoremove运行log，这个策略就没被使用过。。。
其他action的详细情况也不太清楚，希望作者能完善一下。

**Comment by lhbdhr** [comment]
以及action能不能添加多个？应该怎么写配置文件。
比如优先删除不活跃的种子，其次删除上传速度慢的种子，最后删除旧种子
```yml
delete_by_restspace:
      free_space:
        min: 100 # size in GiB
        path: /home/lhbdhr/torrents/qbittorrent/ # This Path MUST EXIST
        action: remove-inactive-seeds remove-slow-upload-seeds remove-old-seeds
```
我修改成了这样，运行没报错，是这么设置吗？
