### ISSUE TITLE
Torrent Deletion Does Not Remove Associated Data

### ISSUE THREAD

**Issue by Sakura9s** [jerrymakesjelly/autoremove-torrents#185]
I am using qbittorrent version 4.3.8 and encountered an issue regarding the deletion of torrents without deleting the associated data.

The torrents were removed from qbittorrent but the files remained.

I'm using Debian 10.
```
my_task:
  client: qbittorrent
  host: http://
  username: 
  password: 
  strategies:
    24hr_free_countdown_strategy:
      excluded_categories:
        - MySaved
      remove: progress < 100 and create_time > 86400 # not finished after 24 hours
    clean_Seeding_S1:
      status:
        - Uploading
      categories:
        - ***
      remove: (leecher < 3 and upload_speed < 50) or (average_uploadspeed < 400)
    clean_Seeding_S2:
      status:
        - Uploading
      categories:
        - ***
      remove: average_uploadspeed < 2 or connected_leecher < 1
    my_strategy:
      ratio: 2
      seed_size:
        limit: 750
        action: remove-inactive-seeds
      delete_data: true
```
