### ISSUE TITLE
Auto Remove Torrents 1.5.5, Cannot run tasks

### ISSUE THREAD

**Issue by bernkasteI** [jerrymakesjelly/autoremove-torrents#191]
I am using Auto Remove Torrents 1.5.5. I created my config.yml and when I try to run  `autoremove-torrents` command I get the following error:

```
Thu, 02 May 2024 03:02:26 autoremovetorrents.main INFO: Auto Remove Torrents 1.5.5
Thu, 02 May 2024 03:02:26 autoremovetorrents.main INFO: Loading configurations...
Thu, 02 May 2024 03:02:26 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Thu, 02 May 2024 03:02:26 autoremovetorrents.task INFO: Running task 'deluge'...
Thu, 02 May 2024 03:02:26 autoremovetorrents.task INFO: Logging in...
Thu, 02 May 2024 03:02:26 autoremovetorrents.main ERROR: AttributeError: 'module' object has no attribute 'PROTOCOL_TLS_CLIENT'
Thu, 02 May 2024 03:02:26 autoremovetorrents.main ERROR: Task deluge fails.
```
I should be using the proper format for strategy and tasks in config.yml so I am not sure what the issue is. Here is what it looks like:

```
deluge:
  client: deluge
  host: IP:Daemon port
  username: <your-username>
  password: <your-password>

  strategies:
    delete_seeds:
      remove: ratio > 1
    clear_space:
          free_space:  
             min: 10
             path: /downloads/deluge
             action: remove-big-seeds
  delete_data: true
```

Any ideas?
