### ISSUE TITLE
Finding 0 torrents in Deluge

### ISSUE THREAD

**Issue by Tyri0n** [jerrymakesjelly/autoremove-torrents#193]
Just installed and can't get it see any torrents in Deluge 2.1.1

Is correctly logging in but is not finding any torrents to process, even though I can see 10 torrents in the web ui.

Any help much appreciated.

```
Tue, 28 May 2024 00:33:24 autoremovetorrents.main INFO: Auto Remove Torrents 1.5.5
Tue, 28 May 2024 00:33:24 autoremovetorrents.main INFO: Loading configurations...
Tue, 28 May 2024 00:33:24 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Tue, 28 May 2024 00:33:24 autoremovetorrents.task INFO: Running task 'my_task'...
Tue, 28 May 2024 00:33:24 autoremovetorrents.task INFO: Logging in...
Tue, 28 May 2024 00:33:24 autoremovetorrents.task INFO: Login successfully. The client is Deluge 2.1.1.
Tue, 28 May 2024 00:33:24 autoremovetorrents.task INFO: WebUI API version: 1
Tue, 28 May 2024 00:33:24 autoremovetorrents.task INFO: Status reported by the client:
        Download Speed: 0.00B/s Total: 1.03MiB
        Upload Speed: 0.00B/s   Total: 497.03MiB
Tue, 28 May 2024 00:33:24 autoremovetorrents.task INFO: Getting all the torrents...
**Tue, 28 May 2024 00:33:24 autoremovetorrents.task INFO: Found 0 torrent(s) in the client**.
Tue, 28 May 2024 00:33:24 autoremovetorrents.strategy INFO: Running strategy my_strategy...
Tue, 28 May 2024 00:33:24 autoremovetorrents.strategy INFO: Total: 0 torrent(s). 0 torrent(s) can be removed.

```

Here's the config:

```
my_task:
  client: Deluge
  host: 127.0.0.1:58846
  username: user
  password: pass
  strategies:
    my_strategy:
      all_categories: true
      all_trackers : true
      all_status: true
      remove: last_activity > 0
  delete_data: true
```

I'm testing by running:
`autoremove-torrents --view`

I installed via pip:
```
Downloading PyYAML-6.0.1.tar.gz (125 kB)
Downloading autoremove_torrents-1.5.5-py3-none-any.whl (47 kB)
```

Many thanks
