### ISSUE TITLE
qbittorrents 种子删除了，下载的内容没删除

### ISSUE THREAD

**Issue by cnkmmk** [jerrymakesjelly/autoremove-torrents#197]
把下载器从TR换到了QBit，autoremove-torrents 版本是1.5.5，在删除的时候只删除了种子，下载的数据没有删除。

配置文件很简单，就是超过4天的就删除

```
my_task:
  client: qbittorrent
  host: http://127.0.0.1:8080
  strategies:
    strategy1:
      all_trackers: true
      create_time: 345600
  delete_data: true
```
