### ISSUE TITLE
Deleting torrents not matching strategy

### ISSUE THREAD

**Issue by cavazos-apps** [jerrymakesjelly/autoremove-torrents#201]
Here is my config:

```
my_task:
  client: qbittorrent
  host: <redacted>>
  username: <redacted>>
  password: <redacted>
  strategies:
    strategy1:
      remove: seeding_time > 21050 or ratio > 2
  delete_data: true
```

The app appears to be removing torrents without making sure the remove criteria have been met.

```
Sat, 18 Jan 2025 09:00:07 autoremovetorrents.strategy INFO: To be deleted:
Sat, 18 Jan 2025 09:00:07 autoremovetorrents.strategy INFO: <torrent_name>.mkv
        Progress:100.00%        Size:4.22GiB    Ratio:0.008     Total Uploaded:34.39MiB
        Seeder(connected/total):0/116   Leecher(connected/total):1/4    Status:Uploading
        Download Speed:0.00B/s(Avg.:654.03KiB/s)        Upload Speed:0.00B/s(Avg.:1.12KiB/s)
        Create Time:2025-01-18 00:16:29 Seeding Time:0d 06:50:18        Downloading Time:(Not Provided) Last Activity:0d 00:29:11
        Category:sonarr
Sat, 18 Jan 2025 09:00:07 autoremovetorrents.task INFO: The torrent <torrent_name>.mkv and its data have been removed.
```

In this case, the ratio was only .008 and the seeding time 6 hours, 50 minutes, neither of which meet the criteria.
