### ISSUE TITLE
I can't use trackers and categories filter togheter

### ISSUE THREAD

**Issue by Jorman** [jerrymakesjelly/autoremove-torrents#38]
Hi, I just found this and I think is very good, I made a little configuration to start but I can't find a way to configure categories and trackers to work together, this's my configuration:
```
my_task:
  client: qbittorrent
  host: http://127.0.0.1:8081
  strategies:
    Torrenting:
      categories:
        - FreeLeech
      trackers:
        - shareisland.org
      ratio: 1
      seeding_time: 432000 # 5 days
      # remove: seeding_time > 432000 or ratio > 1
  delete_data: true
```
I've all freeleech torrent in one category and I want to filter only some tracker so I added this tracker but don't seem to work.
Here the full tracker url, directly from qbittorrent
`http://shareisland.org:2710/MYAPIKEY/announce`

What I do wrong?

J
