### ISSUE TITLE
windows utorrent 连接失败：server 404

### ISSUE THREAD

**Issue by drawwon** [jerrymakesjelly/autoremove-torrents#56]
```
C:\Users\xxx>autoremove-torrents --conf=D:\autoremove-torrents\config.yml
Sat, 11 Jan 2020 14:48:53 autoremovetorrents.main INFO: Auto Remove Torrents 1.4.8
Sat, 11 Jan 2020 14:48:53 autoremovetorrents.main INFO: Loading configurations...
Sat, 11 Jan 2020 14:48:53 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Sat, 11 Jan 2020 14:48:53 autoremovetorrents.task INFO: Running task 'my_task'...
Sat, 11 Jan 2020 14:48:53 autoremovetorrents.task INFO: Logging in...
Sat, 11 Jan 2020 14:48:53 autoremovetorrents.main ERROR: autoremovetorrents.exception.remotefailure.RemoteFailure: The server responsed 404.
Sat, 11 Jan 2020 14:48:53 autoremovetorrents.main ERROR: Task my_task fails.
```

配置文件如下
```yaml
my_task:
  client: utorrent
  host: http://127.0.0.1:10080/gui/
  username: admin
  password: adminadmin
  strategies:
    strategy1:
      all_categories: true
      seed_size:
        limit: 400
        action: remove-old-seeds
  delete_data: true
```

utorrent版本是3.5.5 (build 45505)
