### ISSUE TITLE
free_space and seed_size require last_activity

### ISSUE THREAD

**Issue by LostInsight** [jerrymakesjelly/autoremove-torrents#78]
Tested for deluge 1.3.15 under 1.5.2 with the following config: 
```
 my_task:
   client: deluge
   host: 127.0.0.1:58846
   username: user
   password: pass
   strategies:
     local_limit:
       seed_size:
         limit: 1200
         action: remove-inactive-seeds
   delete_data: true
```

And errors appeared and said
```
Sat, 01 Aug 2020 01:21:11 autoremovetorrents.strategy INFO: Running strategy local_limit...
Sat, 01 Aug 2020 01:21:11 autoremovetorrents.main ERROR: autoremovetorrents.exception.unsupportedproperty.UnsupportedProperty: 'Torrent' object has no attribute 'last_activity'. Your client may not support this property, so the condition seed_size does not work.
Sat, 01 Aug 2020 01:21:11 autoremovetorrents.main ERROR: Task my_task fails. 
```

Same happened for free_space. I know deluge does not have last_activity property but I assume this property is not needed when calculating size.
