### ISSUE TITLE
TypeError fail

### ISSUE THREAD

**Issue by gibboireland** [jerrymakesjelly/autoremove-torrents#84]
Hi there,

Appreciate any help in case Im doing something silly.

Config file seems fine but I keep getting this error when I try to run autoremove torrents:

Fri, 11 Sep 2020 13:10:43 autoremovetorrents.main ERROR: TypeError: argument of type 'NoneType' is not iterable
Fri, 11 Sep 2020 13:10:43 autoremovetorrents.main ERROR: Task my_task fails. 
Fri, 11 Sep 2020 13:10:43 autoremovetorrents.main ERROR: TypeError: argument of type 'bool' is not iterable
Fri, 11 Sep 2020 13:10:43 autoremovetorrents.main ERROR: Task delete_data fails. 

Any help/guidance appreciated.

Thanks indeed,
Gib

**Comment by gibboireland** [comment]
Config file in case it helps:

# A task block
my_task:          # Part 1: iMacHub
  # Part 2: Login Information
  client: qbittorrent
  host: http://192.168.86.66:8080
  username: admin
  password: whatmypasswordis
  # Part 3: Strategies Block (Remove Conditions)
  strategies:
    strategy1:    # Part I: Movies
      # Part II: Filters
status: uploading
      # Part III: Remove Condition
seeding_time: 600
  # Part 4: Decide whether to remove and delete data (optional)
action: remove-old-seeds
delete_data: false

# Add more tasks here...

**Comment by czqdavid** [comment]
I got the same error.  For my case, it's the indent problem of 'delete_data'. Aligning 'delete_data' with the argument  "strategies" solved my problem.

**Comment by jerrymakesjelly** [comment]
You didn't align the configurations properly. Based on your configuration, a correct version is

```yaml
# A task block
my_task:          # Part 1: iMacHub
  # Part 2: Login Information
  client: qbittorrent
  host: http://192.168.86.66:8080
  username: admin
  password: whatmypasswordis
  # Part 3: Strategies Block (Remove Conditions)
  strategies:
    strategy1:    # Part I: Movies
      # Part II: Filters
      status: uploading
      # Part III: Remove Condition
      seeding_time: 600
  # Part 4: Decide whether to remove and delete data (optional)
  action: remove-old-seeds
  delete_data: false

# Add more tasks here...
```
