### ISSUE TITLE
AttributeError: 'Torrent' object has no attribute 'category'

### ISSUE THREAD

**Issue by Jorman** [jerrymakesjelly/autoremove-torrents#97]
Hi, I'm having some problem with 1.5.2 and transmission, see the log
```
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.main INFO: Auto Remove Torrents 1.5.2
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.main INFO: Loading configurations...
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.task INFO: Running task 'my_task'...
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.task INFO: Logging in...
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.task INFO: Login successfully. The client is Transmission 2.94 (d8e60ee44f).
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.task INFO: WebUI API version: 15
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.task INFO: Getting all the torrents...
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.task INFO: Found 16 torrent(s) in the client.
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.strategy INFO: Running strategy Private-Tracker-Torrenting...
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.main ERROR: AttributeError: 'Torrent' object has no attribute 'category'
Sat, 12 Dec 2020 23:53:37 autoremovetorrents.main ERROR: Task my_task fails.
```
this's part of configuration
```
my_task:
  client: transmission
  host: http://127.0.0.1:9091
  strategies:
    Private-Tracker-Torrenting:
      categories:
        - film
        - freeleech
        - tv
      trackers:
        - tt.jumbohostpro.eu
        - t.connecting.center
      status: StalledUpload
      remove: seeding_time > 302400 and last_activity > 172800
  delete_data: true
```
And this's the screen from transmission
![image](https://user-images.githubusercontent.com/5203988/101998858-3a60f500-3cd7-11eb-9a47-858b802f3f75.png)

Do you have any idea?
